"""initial schema

Revision ID: 156bc3da2c48
Revises: 
Create Date: 2026-04-17 18:00:44.391051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '156bc3da2c48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='userrole'), server_default='OWNER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_user_id'), 'ai_tasks', ['user_id'], unique=False)
    op.create_table('inventory_locations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('location_type', sa.Enum('OWN_WAREHOUSE', 'THIRD_PARTY_LOGISTICS', 'SUPPLIER', 'VIRTUAL', name='locationtype'), server_default='OWN_WAREHOUSE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_locations_user_id'), 'inventory_locations', ['user_id'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.Enum('EBAY_PROMOTED', 'AMAZON_PPC', 'GOOGLE_ADS', 'FACEBOOK_ADS', 'TIKTOK_ADS', 'SOCIAL_POST', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), server_default='DRAFT', nullable=False),
    sa.Column('budget_daily', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='AUD', nullable=False),
    sa.Column('target_products', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ad_copy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_campaigns_user_id'), 'marketing_campaigns', ['user_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('EBAY', 'AMAZON', 'SHOPIFY', 'TIKTOK', 'HARVEY_NORMAN', name='platform'), nullable=False),
    sa.Column('region', sa.String(length=5), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'region', name='uq_platform_connection_user_platform_region')
    )
    op.create_index(op.f('ix_platform_connections_user_id'), 'platform_connections', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('dimensions_cm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('country_of_origin', sa.String(length=2), nullable=True),
    sa.Column('sourcing_mode', sa.Enum('ALIBABA_1688', 'ALIBABA_INTL', 'DOMESTIC_AGENCY', 'DROPSHIP', 'OWN_INVENTORY', name='sourcingmode'), nullable=False),
    sa.Column('sourcing_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('base_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_cost_currency', sa.String(length=3), server_default='CNY', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatus'), server_default='DRAFT', nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_point', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_inventory_product_location')
    )
    op.create_index(op.f('ix_inventory_items_location_id'), 'inventory_items', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_id'), 'inventory_items', ['product_id'], unique=False)
    op.create_table('listings',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('EBAY', 'AMAZON', 'SHOPIFY', 'TIKTOK', 'HARVEY_NORMAN', name='platform'), nullable=False),
    sa.Column('region', sa.String(length=5), nullable=False),
    sa.Column('external_listing_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'PAUSED', 'ERROR', 'ENDED', name='listingstatus'), server_default='DRAFT', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='AUD', nullable=False),
    sa.Column('platform_category_id', sa.String(length=255), nullable=True),
    sa.Column('platform_specific', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('pricing_strategy', sa.Enum('FIXED', 'COST_PLUS', 'COMPETITOR_MATCH', 'AI_DYNAMIC', name='pricingstrategy'), server_default='FIXED', nullable=False),
    sa.Column('pricing_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id', 'external_listing_id', name='uq_listing_platform_external')
    )
    op.create_index(op.f('ix_listings_platform_connection_id'), 'listings', ['platform_connection_id'], unique=False)
    op.create_index(op.f('ix_listings_product_id'), 'listings', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('EBAY', 'AMAZON', 'SHOPIFY', 'TIKTOK', 'HARVEY_NORMAN', name='platform'), nullable=True),
    sa.Column('region', sa.String(length=5), nullable=True),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'AWAITING_SHIPMENT', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED', name='orderstatus'), server_default='NEW', nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('platform_fees', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='AUD', nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'), server_default='PENDING', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_translations',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('seo_keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'locale', name='uq_product_translation_locale')
    )
    op.create_index(op.f('ix_product_translations_product_id'), 'product_translations', ['product_id'], unique=False)
    op.create_table('customer_messages',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('EBAY', 'AMAZON', 'SHOPIFY', 'TIKTOK', 'HARVEY_NORMAN', name='platform'), nullable=False),
    sa.Column('external_thread_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('SHIPPING_STATUS', 'RETURN_REQUEST', 'PRODUCT_QUESTION', 'COMPLAINT', 'GENERAL', 'UNKNOWN', name='messageintent'), server_default='UNKNOWN', nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('requires_human', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_draft_response', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_messages_order_id'), 'customer_messages', ['order_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'ADJUSTMENT', 'RETURN_STOCK', 'TRANSFER', name='movementtype'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_table('order_line_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('label_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('LABEL_CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', name='shipmentstatus'), server_default='LABEL_CREATED', nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customs_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('order_line_items')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_customer_messages_order_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    op.drop_index(op.f('ix_product_translations_product_id'), table_name='product_translations')
    op.drop_table('product_translations')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_listings_product_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_platform_connection_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_inventory_items_product_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_location_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_platform_connections_user_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_marketing_campaigns_user_id'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_inventory_locations_user_id'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_index(op.f('ix_ai_tasks_user_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
